process/connections.go
process/dns.go
process/dns_test.go
process/dns_v1.go
process/tags.go
process/tags_test.go
process/tags_v2.go

This will allow us to avoid allocating intermediate slices in situations that don't warrant it.

Add Iterate methods for Tags & DNS

---

process/message.go
process/message_test.go

To be used in https://github.com/DataDog/datadog-agent/pull/6111 or other places

Add stringer interface to MessageType

---

go.mod
go.sum
process/message.go

Support compressing/decompressing msgs with zstd 1.x

---

process/connections.go
process/tags.go
process/tags_test.go
process/tags_v2.go

This will allow iterating host/resource tags without allocating
@DataDog/networks

Add UnsafeIterateTags

---

process/message.go

Adds missing switching logic for the new k8s namespace resource. Necessary for encoding.

[orchestration] add message switching for namespaces

---

README.md
Rakefile
go.mod

[rake] add gimme for default task 

---

process/message.go

[orchestrator] Add VPA collectors to message

---

.github/CODEOWNERS

Update CODEOWNERS file to add co-owners for messages managed by other teams

---

.github/pull_request_template.md

Apply some much-needed improvements to the PR template. Changes are based on the `DataDog/datadog-agent` PR template.

[github] Update `pull_request_template.md`

---

process/dns_v2.go

This PR modifies the error format for when the domain name length is 0 (empty string). This allows error comparison in other packages. 

[backend] Modify error formatting for domain namelen of 0

---

README.md

Add a section to `README.md` on how to publish a new release

Add section for publishing changes

---

process/message.go

It's a followup PR of https://github.com/DataDog/agent-payload/pull/281 to add TypeCollectorECSTask 

add TypeCollectorECSTask

---

.github/CODEOWNERS

Update the CODEOWNERS for the logs and metrics protobufs to the Agent Processing and Routing team.
We are taking over ownership of these from Agent Metrics Logs.
We'll need to be given `write` access to this repository.

Update the CODEOWNERS for metrics and logs protobufs to APR

---

Rakefile

...instead of using latest.  This makes our builds more reproducible.
It also avoids an annoying developer experience where a new protobuf compiler releases, and CI breaks because the checked in code does not match what the latest protobuf generate emits exactly.

Pin protobuf generator versions

---

.gitattributes

Whenever we make a change in the agent payload, the diff github shows includes changes to proto_builder.go files which are autogenerated by gostreamer.

[process payload] Mark *.proto_builder.go libraries as generated

---

proto/process/BUILD.bazel

This PR adds the `connections.proto` file to the `agent_proto` Bazel target so it can be imported by external dependencies. The extended `proto_library` was introduced by https://github.com/DataDog/agent-payload/pull/259.
Export `connections.proto` to be used outside of agent-payload. 

Add connections.proto to agent_proto proto_library

---

.github/CODEOWNERS

- Update @DataDog/processes to @DataDog/container-intake in CODEOWNERS file to reflect the new team name
- Add @DataDog/container-intake to contimage payloads

[CODEOWNERS] Update processes to container-intake

---

.github/CODEOWNERS

Updates ownership of logs and metrics payloads.
Agent Processing and Routing and Agent Metrics Logs were reorganized into Agent Log Pipelines and Agent Metric Pipelines.

Update CODEOWNERs from Agent pipelines split

---

process/message.go

https://github.com/DataDog/agent-payload/issues/373

Fix issues

---

.github/CODEOWNERS

The @DataDog/container-intake team has merged into @DataDog/container-experiences, update CODEOWNERS to reflect the change

[CODEOWNERS] Rename container-intake team to container-experiences
