DataDog/agent-payload

agent_payload.proto
go/agent_payload.pb.go
python/agent_payload_pb2.py

This is part of a change to add a Kubernetes metadata provider in Agent 6. We would also use this in the process-agent in the short-term as we add more functionality around containers (the process pipeline already speaks protobuf).

Add Kubernetes metadata payload definition

---

Gopkg.lock
Gopkg.toml
process/message.go

This allows the zstd dependency to be properly overridden by projects that depend on this one

Remove overridden zstd dependency to avoid transitive dep conflicts

---

proto/logs/logs.go
proto/metrics/metrics.go
proto/process/agent.go

This is a hack for `go mod` support. As this is a known issue the tool does not download and cache any directories that do not contain go files.

`go mod` hack to make protobuf dependencies work with go modules

---

Gopkg.lock
Gopkg.toml

This will allow projects that import this library as well as mmh3 to choose a different, but compatible, mmh3 version

Use a proper version for mmh3 to better help resolve version conflicts

---

process/connections.go
process/dns.go
process/dns_test.go
process/dns_v1.go

This PR adds a function to extract encoded DNS names from the `CollectorConnections` payload.

Extract encoded dns names

---

process/connections.go
process/dns.go
process/dns_test.go

This will allow them to be used independently of `CollectorConnections`
@DataDog/networks

Export GetDNS & IterateDNS

---

process/dns.go
process/dns_test.go
process/dns_v1.go

This will allow iterating DNS entries without allocating strings for them

Add UnsafeIterateDNS

---

Gopkg.lock
Gopkg.toml
process/message.go

zstd `v0.5.x` is not compatible with current `v1.x` version. 
In ought to migrate other repositories that depend on to `v1.x` we need to update package name and import path to avoid symbol collision.

switch zstd path to github.com/DataDog/zstd_0

---

Gopkg.lock

This has basically no performance impact, but gets us to a
properly-licensed version.
```
name                         old time/op    new time/op    delta
DNSDecode/samples.txt-8         184µs ± 5%     184µs ± 5%    ~     (p=0.795 n=19+19)
DNSDecode/big_ips.txt-8        33.1µs ±10%    32.6µs ± 7%    ~     (p=0.421 n=21+19)
DNSDecode/big_entries.txt-8    31.9µs ± 9%    32.4µs ± 3%    ~     (p=0.057 n=21+18)
DNSEncode/samples.txt-8         348µs ± 7%     352µs ± 7%    ~     (p=0.142 n=21+20)
DNSEncode/big_ips.txt-8        27.5µs ± 1%    28.3µs ± 4%  +2.65%  (p=0.000 n=16+18)
DNSEncode/big_entries.txt-8    29.1µs ± 4%    28.4µs ± 1%  -2.57%  (p=0.000 n=11+20)
name                         old alloc/op   new alloc/op   delta
DNSDecode/samples.txt-8        45.0kB ± 0%    45.0kB ± 0%    ~ …
```

Upgrade github.com/DataDog/mmh3 to 1.2.0

---

process/connections.go
process/dns_v2.go

We are seeing some payloads panic due to reading past the end of the domain database.
This commit also surfaces errors that occur during iteration
@DataDog/networks

Improve error handling on DNS v2 read path

---

process/dns_v2.go
process/dns_v2_test.go

The offset of the middle entry of the dns database is being encoded,
but not used (was originally left for future optimization).
However, it has a problem of the result changing its own position.
This works, except in a very specific boundary case.
if offsetOfMiddle happens to be 127 (or any other subsequent size
that causes the size of a varint to go up), we have an off-by-one bug.
The offset is 127, so we compute the size (which is 1), and then increment
the buffer size to match. However, since the offsetOfMiddle is now 128, the
size of the varint is now 2, and the whole buffer's whacked.  Only when the
middle happens to be on the boundary of when the varint size changes.

Fixes intermittent encoding problem.

---

.github/workflows/codeql-analysis.yml

Static code analysis on agent-payload using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.

Setting up codescanning for agent-payload

---

proto/process/agent.proto

One character misspell fix. This is causing some issues in datadog-agent when `misspell` runs, failing the CI.

[doc] fix misspell in protobuf comment

---

process/connections.go

This will allow for allocation-free iteration of the per-connection tag data
@DataDog/networks

[networks] Add UnsafeIterateConnectionTags

---

process/message.go

We are changing manifest payload encoding/decoding to match what is done on other orchestrator payloads.
This is needed for the next RC of 7.40 (https://github.com/DataDog/datadog-agent/pull/13713)

Use regular encoding/decoding for manifest payloads

---

process/dns_test.go
process/dns_v1.go
process/dns_v2.go
process/dns_v2_test.go
process/tags.go
process/tags_test.go
process/tags_v2.go
process/tags_v2_test.go

I added a checks to avoid an out of index range for tags and dns. This came to light after a pentest.

Checks that buffers have enough bytes to parse and iterate

---

Rakefile
process/dns.go
process/dns_v1.go
process/dns_v2.go
process/dns_v2_test.go

Add fuzz testing on top of DNS serialization. `fuzz` testing is a  technique newly added to Go which will, given a test and inputs to that test, mutate that test and attempt to find non graceful failures. Read more [here](https://go.dev/security/fuzz/)
To run the new fuzz test, either run `rake fuzz` or a particular test with `go test -fuzztime 20s -fuzz FuzzIterateDNSV2 ./process` 
This PR includes several pieces:
* commenting and splitting DNSEncoder into two interfaces: this change is purely to make the dns.go file easier to follow. DNSEncoder has two implementations -- V1DNSEncoder which implements Encode and V2DNSEncoder   which implements domain database. Since the methods implemented by both implementations are totally separate, there's no reason to have a shared interface
* adding …

Add some fuzzing on dns 

---

process/tags_test.go
process/tags_v2.go
process/tags_v2_test.go

This PR adds fuzz testing for the unsafe iteration of tags. `fuzz` mutates test inputs to find edge cases. After running the fuzz tests I also added checks `unsafeIterateV2`.

[NET-2833] adds fuzz testing on tags

---

.github/workflows/test.yml
README.md
contlcycle/contlcycle.pb.go
go.mod
gogen/agent_payload.pb.go
pb/agent_logs_payload.pb.go

The `main` branch had not had `rake codegen` run correctly, so this also includes the results of such a run.

Run tests and codegen in CI

---

.github/pull_request_template.md
REVIEWING.md

The `agent-shared-components` team is assigned to review changes to this repo, but has very little experience with the repo and nobody on the team really knows what to look for.
I've written some things down here, but ideally this doc would get filled out a bit more before (or after) this PR lands.

Add a start at review guidelines

---

go.mod

When creating a release for v5.0.49 a release was accidentally create for v5.0.59. Adding a retract to go.mod so depdency managers don't try to upgrade to this version

Add a retract for v5.0.59

---

process/agent.pb.go

Re-run `rake codegen` due to concurrent of #311 and #302
Fix CI.
Go version has impact on generated spaces/newlines.

Regen from master due to Go version chnge

---

.gitignore
Rakefile

Adds a `rake setup_gogo` task which will clone gogo into a new toolchains directory (which is git ignored).
On every run of codegen, we'll checkout a pinned version of gogo and rebuild it. This should be pretty fast as long as gogo is already checked out.
This PR also adds a new 'toolchains' location where all dependencies are cached. Before we were jumbling a bunch of dependencies into /tmp.
This led to a weird case where we were accidentally (?) using a new protobuf compiler with a legacy .proto library (for stuff like google.Duration). This is now explicit.
The structure of the new toolchains is described in the Rakefile

Avoid redownloading all dependencies (protoc, gogo)

---

Rakefile

For go code generation (since we use external plugins in all cases) there's no difference between the legacy and mainline protobuf compiler.
This is safe because we can re-run the codegen and get exact same code out.
This change updates to the mainline protobuf compiler wherever we can.

Remove more remaining uses of protoc_legacy_binary for go codegen

---

Rakefile
autoscaling/kubernetes/autoscaling.pb.go
contimage/contimage.pb.go

This updates contlcycle, autoscaling, and contimage to generate their payloads using non-deprecated shared protobuf definitions. This will help us reduce some cruft in the build script.
The changes are wire compatible, but the generated go code might not compile cleanly into the agent/backend.
See for context
* https://github.com/DataDog/agent-payload/pull/337
* https://github.com/DataDog/agent-payload/pull/342

Update container-app to use newer include files

---

Rakefile

As described in https://github.com/DataDog/agent-payload/pull/337 we used to use two different protobuf compilers in this repo.
Now we only use one, so we can get rid of references to the old one.

[protobuf] remove legacy protobuf compiler
